services:
  minio:
    image: minio/minio
    container_name: flaskdrive_minio
    hostname: flaskdrive_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: tungt_minio
      MINIO_ROOT_PASSWORD: minio_password
    command: server --console-address ":9001" /data
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
